### ISSUE TITLE
Max 12 images?

### ISSUE THREAD

**Issue by GitHuug** [jsanahuja/InstagramFeed#25] opened 2020-04-28 07:44 UTC
Hi there!

As an teacher, I want to give my students the opportunity to have a simple online portfolio combined with Instagram. I found your github, thanks for this!!

I changed a bit to make it easier for my first year students to understand the code.
Now I've got a problem, I only can place max 12 images. The standard was 8 images, I changed this to 100, but I've only got 12 max.

I didn't change anything in the JS.

Here is the HTML with the edits in it

https://www.imgdumper.nl/uploads9/5ea7ea67e846e/5ea7ea67e020f-Screenshot_2020-04-28_at_10.33.16.png

What am I missing?

**Comment by GitHuug** [comment] 2020-04-28 08:36
Ohw, now I see, its up to 12 for users...
Is there a way to upgrade this one to get the whole feed?

**Comment by UltraPublishing** [comment] 2020-04-28 19:19
Duplicate of #1

**Closed as completed** 2020-05-05 12:30 UTC
Labels: 05 ISSUE: Duplicate
