### ISSUE TITLE
Filter tags?

### ISSUE THREAD

**Issue by geheimerEichkater** [jsanahuja/InstagramFeed#35] opened 2020-07-28 13:27 UTC
Hey Javier, 
is there a way to sort out hashtags? Like, I would like to see "#green" but I would like to exclude those pics, that have also been tagged with "#ecological"?

**Comment by jsanahuja** [comment] 2020-07-30 08:03
Duplicate of #22

**Closed as completed by jsanahuja** 2020-07-30 08:03 UTC
Labels: 04 ISSUE: Question, 05 ISSUE: Duplicate
