### ISSUE TITLE
Stopped working for username tag

### ISSUE THREAD

**Issue by gcampedelli** [jsanahuja/InstagramFeed#15] opened 2020-03-16 14:23 UTC
Hello, I was using it and it only works now while fetching the tag. Username is not working anymore.

**Comment by jsanahuja** [comment] 2020-03-16 21:44
This is caused by a kind of network soft ban from Instagram. You may have done a lot of requests.
It does not affect your website, only you.

See jsanahuja/jquery.instagramFeed#25

**Comment by gcampedelli** [comment] 2020-03-16 22:20
I was testing in Codepen. But it looks like it not working in my site either and as well in your demos. Only with tags.

**Comment by jsanahuja** [comment] 2020-03-18 15:36
This is a **client-side** library so if your network gets temporary banned, it won't work either in Codepen, our demos nor localhost BUT that only affects you, not your visitors.

This often happens during development because of several page reloads.

**Comment by brnpimentel** [comment] 2020-03-28 00:41
I think it stopped working today. The demos is not working too

**Comment by gcampedelli** [comment] 2020-03-28 00:54
Hi @brnmonteiro , it is really like he said. Try to change your ip or conect yourself in another wifi network and you will it again.

**Comment by gcampedelli** [comment] 2020-03-28 00:55
Sorry, if this works for you, please close this issue.

**Comment by brnpimentel** [comment] 2020-03-28 00:56
Its true. I reboot my modem and back to normal. Sorry.

**Comment by brnpimentel** [comment] 2020-03-28 00:57
You can close this issue. I can't close here. Thanks

**Closed as completed** 2020-03-28 00:58 UTC
Labels: 08 ISSUE: Support, 10 ISSUE: Third party

**Comment by dhruveonmars** [comment] 2020-04-29 11:31
When your network gets soft-banned, does it happen for a specific username or for the whole feed? Because the demo pages still work for me, though I get this error in my console now; `TypeError: undefined is not an object (evaluating 'a[1].split')`

**Comment by jsanahuja** [comment] 2020-04-29 15:13
Happens for the whole feed as far as I know. Please create a new issue with the IG username and I will check it out

Thanks
